sudo: required
services:
 - docker
before_install:
 - docker build -t balasubramanian/multidocker-reacttest -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true balasubramanian/multidocker-reacttest npm run test -- --coverage
 
after_success:
 - docker build -t balasubramanian/multi-client ./client
 - docker build -t balasubramanian/multi-nginx ./nginx
 - docker build -t balasubramanian/multi-server ./server
 - docker build -t balasubramanian/multi-worker ./worker
 ####docker push to docker hub, we need to login first to dockerhub####
 # ###specify the credentials as Env Variable in Travis CI###
 - echo "$DOCKER_PASS" | docker login -u "$DOCKER_HUB_ID" --password-stdin
 - docker push balasubramanian/multi-client
 - docker push balasubramanian/multi-nginx
 - docker push balasubramanian/multi-server
 - docker push balasubramanian/multi-worker

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "MultiDocker"
 env: "Multidocker-env"
 bucket_name: "elasticbeanstalk-us-east-1-465742529921"
 bucket_path: "multidocker"
 on:
  branch: master
 access_key_id:
   secure: "$AWS_ACCESS_KEY"
 secret_access_key:
   secure: "$AWS_SCERET_KEY"
